<table>
    <thead>
    <tr>
        <th>CAMPANA_COBEFEC</th>
        <th>DOCUMENTO</th>
        <th>ID_CUENTA</th>
        <th>NUMERO_CUENTA</th>
        <th>NOMBRES_COMPLETOS</th>
        <th>MODELO_VEHICULO</th>
        <th>NUMERO_CONVENIOS</th>
        <th>NUMEROS_MULTAS</th>
        <th>PLACA_VEHICULO</th>
        <th>SCORE_INFRACTOR</th>
        <th>TIPO_CARTERA</th>
        <th>DESCRIPCION_INFRACCION</th>
        <th>DIAS_MORA</th>
        <th>AGENTE_ACTUAL</th>
        <th>CUOTAS_PENDIENTES_CONVENIO</th>
        <th>SALDO_INICIAL</th>
        <th>TOTAL_A_PAGAR_INFRACTOR</th>
        <th>CUENTA_FECHA_ACTUALIZACION</th>
        <th>VALOR_CUOTA_CONVENIO</th>
        <th>VALOR_MULTAS</th>
        <th>VALOR_TOTAL_CONVENIO</th>
        <th>ABONO</th>
        <th>TELEFONO1</th>
        <th>TELEFONO2</th>
        <th>TELEFONO3</th>
        <th>TELEFONO4</th>
        <th>TELEFONO5</th>
        <th>TELEFONO6</th>
        <th>TELEFONO7</th>
        <th>TELEFONO8</th>
        <th>ESTADO_SISTEMA</th>
        <th>FECHA_COACTIVA</th>
        <th>FECHA_INICIO_CUOTA_CONVENIO</th>
        <th>FOCALIZADO</th>
        <th>TLC_ULTIMA_GESTION_ACCION</th>
        <th>TLC_ULTIMA_GESTION_AGENTE</th>
        <th>TLC_ULTIMA_GESTION_FECHA</th>
        <th>TLC_ULTIMA_GESTION_HORA</th>
        <th>TLC_ULTIMA_GESTION_TIPO</th>
        <th>TLC_ULTIMA_GESTION_DESCRIPCION</th>
        <th>TLC_ULTIMA_GESTION_TELEFONO</th>
        <th>TLC_ULTIMA_GESTION_MOTIVO</th>
        <th>TLC_ULTIMA_GESTION_SUBACCION</th>
        <th>TLC_ULTIMA_GESTION_SUBMOTIVO</th>
        <th>TLC_ULTIMA_GESTION_PESO</th>
        <th>TLC_MEJOR_GESTION_ACCION</th>
        <th>TLC_MEJOR_GESTION_AGENTE</th>
        <th>TLC_MEJOR_GESTION_TIPO</th>
        <th>TLC_MEJOR_GESTION_FECHA</th>
        <th>TLC_MEJOR_GESTION_DESCRIPCION</th>
        <th>TLC_MEJOR_GESTION_TELEFONO</th>
        <th>TLC_MEJOR_GESTION_MOTIVO</th>
        <th>TLC_MEJOR_GESTION_SUBACCION</th>
        <th>TLC_MEJOR_GESTION_SUBMOTIVO</th>
        <th>TLC_MEJOR_GESTION_HORA</th>
        <th>TLC_MEJOR_GESTION_PESO</th>
        <th>CEX_MEJOR_GESTION_ACCION</th>
        <th>CEX_MEJOR_GESTION_FECHA</th>
        <th>CEX_MEJOR_GESTION_TIPO</th>
        <th>CEX_MEJOR_GESTION_DESCRIPCION</th>
        <th>CEX_MEJOR_GESTION_TELEFONO</th>
        <th>CEX_MEJOR_GESTION_SUBACCION</th>
        <th>CEX_MEJOR_GESTION_PESO</th>
        <th>GESTIONES_CEX</th>
        <th>GESTIONES_TLC</th>
    </tr>
    </thead>
    <tbody>
    @foreach($reportes as $reporte)
    <tr>
        <td>{{$reporte['CAMPANA_COBEFEC']}}</td>
        <td>{{$reporte['DOCUMENTO']}}</td>
        <td>{{$reporte['ID_CUENTA']}}</td>
        <td>{{$reporte['NUMERO_CUENTA']}}</td>
        <td>{{$reporte['NOMBRES_COMPLETOS']}}</td>
        <td>{{$reporte['MODELO_VEHICULO']}}</td>
        <td>{{$reporte['NUMERO_CONVENIOS']}}</td>
        <td>{{$reporte['NUMEROS_MULTAS']}}</td>
        <td>{{$reporte['PLACA_VEHICULO']}}</td>
        <td>{{$reporte['SCORE_INFRACTOR']}}</td>
        <td>{{$reporte['TIPO_CARTERA']}}</td>
        <td>{{$reporte['DESCRIPCION_INFRACCION']}}</td>
        <td>{{$reporte['DIAS_MORA']}}</td>
        <td>{{$reporte['AGENTE_ACTUAL']}}</td>
        <td>{{$reporte['CUOTAS_PENDIENTES_CONVENIO']}}</td>
        <td>{{$reporte['SALDO_INICIAL']}}</td>
        <td>{{$reporte['TOTAL_A_PAGAR_INFRACTOR']}}</td>
        <td>{{$reporte['CUENTA_FECHA_ACTUALIZACION']}}</td>
        <td>{{$reporte['VALOR_CUOTA_CONVENIO']}}</td>
        <td>{{$reporte['VALOR_MULTAS']}}</td>
        <td>{{$reporte['VALOR_TOTAL_CONVENIO']}}</td>
        <td>{{$reporte['ABONO']}}</td>
        <td>{{$reporte['TELEFONO1']}}</td>
        <td>{{$reporte['TELEFONO2']}}</td>
        <td>{{$reporte['TELEFONO3']}}</td>
        <td>{{$reporte['TELEFONO4']}}</td>
        <td>{{$reporte['TELEFONO5']}}</td>
        <td>{{$reporte['TELEFONO6']}}</td>
        <td>{{$reporte['TELEFONO7']}}</td>
        <td>{{$reporte['TELEFONO8']}}</td>
        <td>{{$reporte['ESTADO_SISTEMA']}}</td>
        <td>{{$reporte['FECHA_COACTIVA']}}</td>
        <td>{{$reporte['FECHA_INICIO_CUOTA_CONVENIO']}}</td>
        <td>{{$reporte['FOCALIZADO']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_ACCION']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_AGENTE']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_FECHA']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_HORA']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_TIPO']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_DESCRIPCION']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_TELEFONO']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_MOTIVO']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_SUBACCION']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_SUBMOTIVO']}}</td>
        <td>{{$reporte['TLC_ULTIMA_GESTION_PESO']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_ACCION']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_AGENTE']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_TIPO']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_FECHA']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_DESCRIPCION']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_TELEFONO']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_MOTIVO']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_SUBACCION']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_SUBMOTIVO']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_HORA']}}</td>
        <td>{{$reporte['TLC_MEJOR_GESTION_PESO']}}</td>
        <td>{{$reporte['CEX_MEJOR_GESTION_ACCION']}}</td>
        <td>{{$reporte['CEX_MEJOR_GESTION_FECHA']}}</td>
        <td>{{$reporte['CEX_MEJOR_GESTION_TIPO']}}</td>
        <td>{{$reporte['CEX_MEJOR_GESTION_DESCRIPCION']}}</td>
        <td>{{$reporte['CEX_MEJOR_GESTION_TELEFONO']}}</td>
        <td>{{$reporte['CEX_MEJOR_GESTION_SUBACCION']}}</td>
        <td>{{$reporte['CEX_MEJOR_GESTION_PESO']}}</td>
        <td>{{$reporte['GESTIONES_CEX']}}</td>
        <td>{{$reporte['GESTIONES_TLC']}}</td>
    </tr>
    @endforeach
    </tbody>
</table>