<table>
    <thead>
    <tr>
        <th>codpricedsocciclof</th>
        <th>codpri</th>
        <th>ciclof</th>
        <th>cedsoc</th>
        <th>nomsoc</th>
        <th>saldo_inicial</th>
        <th>saldo_actual</th>
        <th>abono</th>
        <th>agente_actual</th>
        <th>tlc_ultima_gestion_fecha</th>
        <th>tlc_ultima_gestion_peso</th>
        <th>tlc_ultima_gestion_accion</th>
        <th>tlc_ultima_gestion_subaccion</th>
        <th>tlc_ultima_gestion_motivo</th>
        <th>tlc_ultima_gestion_submotivo</th>
        <th>tlc_ultima_gestion_descripcion</th>
        <th>pp_fecha</th>
        <th>tlc_mejor_gestion_fecha</th>
        <th>tlc_mejor_gestion_accion</th>
        <th>tlc_mejor_gestion_subaccion</th>
        <th>tlc_mejor_gestion_motivo</th>
        <th>tlc_mejor_gestion_submotivo</th>
        <th>tlc_mejor_gestion_descripcion</th>
        <th>mejor_gestion_pp_fecha</th>
        <th>edcart</th>
        <th>triesgo</th>
        <th>nombre_ciudad</th>
        <th>direccion</th>
        <th>zona</th>
        <th>pendiente_actual_exigible</th>
        <th>pendiente_30d</th>
        <th>pendiente_60d</th>
        <th>pendiente_90d</th>
        <th>pendiente_mas90</th>
        <th>campana</th>
        <th>estado_sistema</th>
        <th>focalizacion</th>
        <th>tlc_ultima_gestion_tipo</th>
        <th>cex_mejor_gestion_peso</th>
        <th>cex_mejor_gestion_accion</th>
        <th>cex_mejor_gestion_subaccion</th>
        <th>cex_mejor_gestion_descripcion</th>
        <th>cex_mejor_gestion_agente</th>
        <th>cex_mejor_gestion_fecha</th>
        <th>cex_mejor_gestion_tipo</th>
        <th>cex_mejor_gestion_direccion</th>
        <th>cobertura</th>
    </tr>
    </thead>
    <tbody>
    @foreach($reportes as $reporte)
    <tr>
        <td>{{$reporte['codpricedsocciclof']}}</td>
        <td>{{$reporte['codpri']}}</td>
        <td>{{$reporte['ciclof']}}</td>
        <td>{{$reporte['cedsoc']}}</td>
        <td>{{$reporte['nomsoc']}}</td>
        <td>{{$reporte['saldo_inicial']}}</td>
        <td>{{$reporte['saldo_actual']}}</td>
        <td>{{$reporte['abono']}}</td>
        <td>{{$reporte['agente_actual']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_fecha']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_peso']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_accion']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_subaccion']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_motivo']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_submotivo']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_descripcion']}}</td>
        <td>{{$reporte['pp_fecha']}}</td>
        <td>{{$reporte['tlc_mejor_gestion_fecha']}}</td>
        <td>{{$reporte['tlc_mejor_gestion_accion']}}</td>
        <td>{{$reporte['tlc_mejor_gestion_subaccion']}}</td>
        <td>{{$reporte['tlc_mejor_gestion_motivo']}}</td>
        <td>{{$reporte['tlc_mejor_gestion_submotivo']}}</td>
        <td>{{$reporte['tlc_mejor_gestion_descripcion']}}</td>
        <td>{{$reporte['mejor_gestion_pp_fecha']}}</td>
        <td>{{$reporte['edcart']}}</td>
        <td>{{$reporte['triesgo']}}</td>
        <td>{{$reporte['nombre_ciudad']}}</td>
        <td>{{$reporte['direccion']}}</td>
        <td>{{$reporte['zona']}}</td>
        <td>{{$reporte['pendiente_actual_exigible']}}</td>
        <td>{{$reporte['pendiente_30d']}}</td>
        <td>{{$reporte['pendiente_60d']}}</td>
        <td>{{$reporte['pendiente_90d']}}</td>
        <td>{{$reporte['pendiente_mas90']}}</td>
        <td>{{$reporte['campana']}}</td>
        <td>{{$reporte['estado_sistema']}}</td>
        <td>{{$reporte['focalizacion']}}</td>
        <td>{{$reporte['tlc_ultima_gestion_tipo']}}</td>
        <td>{{$reporte['cex_mejor_gestion_peso']}}</td>
        <td>{{$reporte['cex_mejor_gestion_accion']}}</td>
        <td>{{$reporte['cex_mejor_gestion_subaccion']}}</td>
        <td>{{$reporte['cex_mejor_gestion_descripcion']}}</td>
        <td>{{$reporte['cex_mejor_gestion_agente']}}</td>
        <td>{{$reporte['cex_mejor_gestion_fecha']}}</td>
        <td>{{$reporte['cex_mejor_gestion_tipo']}}</td>
        <td>{{$reporte['cex_mejor_gestion_direccion']}}</td>
        <td>{{$reporte['cobertura']}}</td>
    </tr>
    @endforeach
    </tbody>
</table>